### ISSUE TITLE
use sparklines to indicate trend

### ISSUE THREAD

**Issue by kjappelbaum** [ltalirz/atomistic-software#39]
https://borisyankov.github.io/react-sparklines/

**Comment by ltalirz** [comment]
thanks for the suggestion! 
the plot obviously needs improvement and I was anyhow looking for alternatives to nivo

there's many other things that could be improved in the app - this is the first time I've really touched javascript in over a decade and I'd be happy for any further tips (e.g. there's currently no autoformatter; I'd like to add one)

**Comment by kjappelbaum** [comment]
i'll give this repo a look soon as I'll do a react table app for the cheminfo app (to replace the static website) i can make PRs with linters etc.

**Comment by ltalirz** [comment]
sparkline example with tooltips https://ej2.syncfusion.com/react/demos/#/material/sparkline/default

**Comment by ltalirz** [comment]
@kjappelbaum by the way, what is the standard approach to impose a certain formatter (like https://www.npmjs.com/package/js-beautify)  in a js package?
is this done via pre-commit hooks as well? or do people do it via the source code editor

**Comment by kjappelbaum** [comment]
we use the rules in https://github.com/cheminfo/eslint-config for eslint and [prettier](https://prettier.io/) (VSCode can highlight them). The [eslint prettier plugin](https://github.com/prettier/eslint-plugin-prettier) can then highlight the prettier issues as eslint rule. 

And the first part of the github action is then something like 


```
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run eslint
```
